[package]
name = "nix-script-directives"
version = "3.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
log = "0.4.26"
rnix = "0.12.0"
rowan = "0.15.16"
serde = { version = "1.0.219", features = [ "derive" ] }
