[package]
name = "nix-script-directives"
version = "3.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
log = "0.4.22"
rnix = "0.11.0"
rowan = "0.15.16"
serde = { version = "1.0.210", features = [ "derive" ] }
