[package]
name = "nix-script-directives"
version = "3.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
log = "0.4.25"
rnix = "0.12.0"
rowan = "0.16.1"
serde = { version = "1.0.217", features = [ "derive" ] }
